# Generated by Django 3.2 on 2024-08-20 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='image',
            field=models.ImageField(default='stories/images/default.jpg', upload_to='stories/images'),
        ),
    ]
