# Generated by Django 3.2 on 2024-08-20 03:32

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_story_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='info',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Text'),
            preserve_default=False,
        ),
    ]
